export const list_home_swiper = [
  "images/home_swiper/home_swiper_img1.jpg",
  "images/home_swiper/home_swiper_img2.jpg",
  "images/home_swiper/home_swiper_img3.jpg",
  "images/home_swiper/home_swiper_img4.jpg",
  "images/home_swiper/home_swiper_img5.jpg",
  "images/home_swiper/home_swiper_img6.jpg",
];

export const companies = [
  "images/companies/company1.png",
  "images/companies/company2.png",
  "images/companies/company3.png",
  "images/companies/company4.png",
  "images/companies/company5.png",
  "images/companies/company6.png",
  "images/companies/company7.png",
  "images/companies/company8.png",
];

export const png_swiper = [
  {
    id: Math.random(),
    picture: "images/pngpictures/png1.png",
    name: "MERCEDES-BENZ G63",
    text: "Lorem ipsum",
    price: 250000,
  },
  {
    id: Math.random(),
    picture: "images/pngpictures/png2.png",
    name: "MERCEDES-BENZ W222",
    text: "Lorem ipsum",
    price: 220000,
  },
  {
    id: Math.random(),
    picture: "images/pngpictures/png3.png",
    name: "MERCEDES-BENZ CLK",
    text: "Lorem ipsum",
    price: 120000,
  },
  {
    id: Math.random(),
    picture: "images/pngpictures/png4.png",
    name: "BMW 530i",
    text: "Lorem ipsum",
    price: 100000,
  },
  {
    id: Math.random(),
    picture: "images/pngpictures/png5.png",
    name: "BMW M2",
    text: "Lorem ipsum",
    price: 135000,
  },
  {
    id: Math.random(),
    picture: "images/pngpictures/png6.png",
    name: "FORD FOCUS",
    text: "Lorem ipsum",
    price: 8000,
  },
  {
    id: Math.random(),
    picture: "images/pngpictures/png7.png",
    name: "FORD ESCAPE",
    text: "Lorem ipsum",
    price: 10000,
  },
];

export const cars = [
  {
    id: Math.random(),
    picture: "images/cars/toyota1.jpg",
    name: "Toyota Corolla 2018",
    vin: "5YFBURHE9JPBM8097",
    date: "2018",
    price: 3800,
    hp: "130",
    gallery: [
      "images/cars/toyota1.jpg",
      "images/cars/toyota2.jpg",
      "images/cars/toyota3.jpg",
      "images/cars/toyota4.jpg",
      "images/cars/toyota5.jpg",
      "images/cars/toyota6.jpg",
      "images/cars/toyota7.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota8.jpg",
    name: "Toyota RAV4 XLE",
    vin: "  2T3C1RfV3PW296301",
    date: "2019",
    price: 17200,
    hp: "190",
    gallery: [
      "images/cars/toyota8.jpg",
      "images/cars/toyota9.jpg",
      "images/cars/toyota10.jpg",
      "images/cars/toyota11.jpg",
      "images/cars/toyota12.jpg",
      "images/cars/toyota13.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota14.jpg",
    name: "Toyota Camry SE 2020",
    vin: "4T1G11AK7LU409731",
    date: "2020",
    price: 8900,
    hp: "178",
    gallery: [
      "images/cars/toyota14.jpg",
      "images/cars/toyota15.jpg",
      "images/cars/toyota16.jpg",
      "images/cars/toyota17.jpg",
      "images/cars/toyota18.jpg",
      "images/cars/toyota19.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota20.jpg",
    name: "Toyota Prius 2012",
    vin: "JTDKDTB39F1P60L46",
    date: "2012",
    price: 3550,
    hp: "141",
    gallery: [
      "images/cars/toyota20.jpg",
      "images/cars/toyota21.jpg",
      "images/cars/toyota22.jpg",
      "images/cars/toyota23.jpg",
      "images/cars/toyota24.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota25.jpg",
    name: "Toyota Sienna 2015",
    vin: "2T6P20LPZ5090LQV9",
    date: "2015",
    price: 8900,
    hp: "230",
    gallery: [
      "images/cars/toyota25.jpg",
      "images/cars/toyota26.jpg",
      "images/cars/toyota27.jpg",
      "images/cars/toyota28.jpg",
      "images/cars/toyota29.jpg",
      "images/cars/toyota30.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota31.jpg",
    name: "Toyota RAV4 LE 2017",
    vin: "2T3ZFREV3HWP6080Q",
    date: "2017",
    price: 7300,
    hp: "141",
    gallery: [
      "images/cars/toyota31.jpg",
      "images/cars/toyota32.jpg",
      "images/cars/toyota33.jpg",
      "images/cars/toyota34.jpg",
      "images/cars/toyota35.jpg",
      "images/cars/toyota36.jpg",
      "images/cars/toyota37.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota38.jpg",
    name: "Toyota Avalon Limited 2019",
    vin: "4T1CA1AB2MUPQ65L9",
    date: "2019",
    price: 6100,
    hp: "178",
    gallery: [
      "images/cars/toyota38.jpg",
      "images/cars/toyota39.jpg",
      "images/cars/toyota40.jpg",
      "images/cars/toyota41.jpg",
      "images/cars/toyota42.jpg",
      "images/cars/toyota43.jpg",
      "images/cars/toyota44.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota45.jpg",
    name: "Toyota Prius 2016",
    vin: "JTDKBRFU7G3L8BO01",
    date: "2018",
    price: 3800,
    hp: "140",
    gallery: [
      "images/cars/toyota45.jpg",
      "images/cars/toyota46.jpg",
      "images/cars/toyota47.jpg",
      "images/cars/toyota48.jpg",
      "images/cars/toyota49.jpg",
      "images/cars/toyota50.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota51.jpg",
    name: "Toyota Scion XB 2013",
    vin: "JTLZE4FE3DJ60L3Z0",
    date: "2013",
    price: 625,
    hp: "101",
    gallery: [
      "images/cars/toyota51.jpg",
      "images/cars/toyota52.jpg",
      "images/cars/toyota53.jpg",
      "images/cars/toyota54.jpg",
      "images/cars/toyota55.jpg",
      "images/cars/toyota56.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota57.jpg",
    name: "Toyota 4RUNNER SRS 2010",
    vin: "JTEZUSJR2A5PL70LQ",
    date: "2018",
    price: 13800,
    hp: "310",
    gallery: [
      "images/cars/toyota57.jpg",
      "images/cars/toyota58.jpg",
      "images/cars/toyota59.jpg",
      "images/cars/toyota60.jpg",
      "images/cars/toyota61.jpg",
      "images/cars/toyota62.jpg",
      "images/cars/toyota63.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota64.jpg",
    name: "Toyota Highlander Limited 2005",
    vin: "JTEEP21A35O901076",
    date: "2005",
    price: 1300,
    hp: "200",
    gallery: [
      "images/cars/toyota64.jpg",
      "images/cars/toyota65.jpg",
      "images/cars/toyota66.jpg",
      "images/cars/toyota67.jpg",
      "images/cars/toyota68.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota69.jpg",
    name: "Toyota Vemza LE 2015",
    vin: "4T3BA3BB6FUC90Q10",
    date: "2015",
    price: 5900,
    hp: "194",
    gallery: [
      "images/cars/toyota69.jpg",
      "images/cars/toyota70.jpg",
      "images/cars/toyota71.jpg",
      "images/cars/toyota72.jpg",
      "images/cars/toyota73.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota74.jpg",
    name: "Toyota Tundra Crewmax SRS 2020",
    vin: "5TFDY5F19LX20Q9M5",
    date: "2020",
    price: 13000,
    hp: "400",
    gallery: [
      "images/cars/toyota74.jpg",
      "images/cars/toyota75.jpg",
      "images/cars/toyota76.jpg",
      "images/cars/toyota77.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota78.jpg",
    name: "Toyota Tacoma Double Cab 2012",
    vin: "5TFJX4GN0CX7P560E",
    date: "2012",
    price: 8300,
    hp: "200",
    gallery: [
      "images/cars/toyota78.jpg",
      "images/cars/toyota79.jpg",
      "images/cars/toyota80.jpg",
      "images/cars/toyota81.jpg",
      "images/cars/toyota83.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota84.jpg",
    name: "Toyota Corolla Base 2012",
    vin: "2T1BU4EE8CC60P780",
    date: "2012",
    price: 1250,
    hp: "132",
    gallery: [
      "images/cars/toyota84.jpg",
      "images/cars/toyota85.jpg",
      "images/cars/toyota86.jpg",
      "images/cars/toyota87.jpg",
      "images/cars/toyota88.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota89.jpg",
    name: "Toyota Camry Base 2010",
    vin: "4T1BF3EK2AUP9307S",
    date: "2010",
    price: 1250,
    hp: "178",
    gallery: [
      "images/cars/toyota89.jpg",
      "images/cars/toyota90.jpg",
      "images/cars/toyota91.jpg",
      "images/cars/toyota92.jpg",
      "images/cars/toyota93.jpg",
      "images/cars/toyota94.jpg",
      "images/cars/toyota95.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota96.jpg",
    name: "Toyota Camry Base 2012",
    vin: "4T1BF3EK2AP10QU901",
    date: "2012",
    price: 1900,
    hp: "180",
    gallery: [
      "images/cars/toyota96.jpg",
      "images/cars/toyota97.jpg",
      "images/cars/toyota98.jpg",
      "images/cars/toyota99.jpg",
      "images/cars/toyota100.jpg",
      "images/cars/toyota101.jpg",
      "images/cars/toyota102.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota103.jpg",
    name: "Toyota RAV4 2008",
    vin: "JTHH20V226POW607",
    date: "2008",
    price: 1200,
    hp: "146",
    gallery: [
      "images/cars/toyota103.jpg",
      "images/cars/toyota104.jpg",
      "images/cars/toyota105.jpg",
      "images/cars/toyota106.jpg",
      "images/cars/toyota107.jpg",
      "images/cars/toyota108.jpg",
      "images/cars/toyota109.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota110.jpg",
    name: "Toyota Corolla Base 2009",
    vin: "1NXBU4EE8CLX60P780",
    date: "2009",
    price: 1250,
    hp: "138",
    gallery: [
      "images/cars/toyota110.jpg",
      "images/cars/toyota111.jpg",
      "images/cars/toyota112.jpg",
      "images/cars/toyota113.jpg",
      "images/cars/toyota114.jpg",
      "images/cars/toyota115.jpg",
      "images/cars/toyota116.jpg",
      "images/cars/toyota117.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota118.jpg",
    name: "Toyota Corolla LE 2020",
    vin: "JTDEPRAE0LJ50LO7A",
    date: "2020",
    price: 20985,
    hp: "150",
    gallery: [
      "images/cars/toyota118.jpg",
      "images/cars/toyota119.jpg",
      "images/cars/toyota120.jpg",
      "images/cars/toyota121.jpg",
      "images/cars/toyota122.jpg",
      "images/cars/toyota123.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota124.jpg",
    name: "Toyota Prius 2005",
    vin: "JTDKB20U553PO6LQ1",
    date: "2005",
    price: 1300,
    hp: "101",
    gallery: [
      "images/cars/toyota124.jpg",
      "images/cars/toyota125.jpg",
      "images/cars/toyota126.jpg",
      "images/cars/toyota127.jpg",
      "images/cars/toyota128.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota129.jpg",
    name: "Toyota Celica GT-S 2002",
    vin: "JTDDY3TO20PQ70M9",
    date: "2002",
    price: 4096,
    hp: "250",
    gallery: [
      "images/cars/toyota129.jpg",
      "images/cars/toyota130.jpg",
      "images/cars/toyota131.jpg",
      "images/cars/toyota132.jpg",
      "images/cars/toyota133.jpg",
      "images/cars/toyota134.jpg",
      "images/cars/toyota135.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota136.jpg",
    name: "Toyota Yaris 2008",
    vin: "JTDBT923584L700JQ",
    date: "2008",
    price: 5100,
    hp: "101",
    gallery: [
      "images/cars/toyota136.jpg",
      "images/cars/toyota137.jpg",
      "images/cars/toyota138.jpg",
      "images/cars/toyota139.jpg",
      "images/cars/toyota140.jpg",
      "images/cars/toyota141.jpg",
      "images/cars/toyota142.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota143.jpg",
    name: "Toyota Venza 2013",
    vin: "4T3BK3BB8DU12BO9A",
    date: "2013",
    price: 14101,
    hp: "230",
    gallery: [
      "images/cars/toyota143.jpg",
      "images/cars/toyota144.jpg",
      "images/cars/toyota145.jpg",
      "images/cars/toyota146.jpg",
      "images/cars/toyota147.jpg",
      "images/cars/toyota148.jpg",
      "images/cars/toyota149.jpg",
      "images/cars/toyota150.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota151.jpg",
    name: "Toyota Camry LE 2017",
    vin: "4T1BF1FK3HUBQ85J1",
    date: "2017",
    price: 12990,
    hp: "180",
    gallery: [
      "images/cars/toyota151.jpg",
      "images/cars/toyota152.jpg",
      "images/cars/toyota153.jpg",
      "images/cars/toyota154.jpg",
      "images/cars/toyota155.jpg",
      "images/cars/toyota156.jpg",
      "images/cars/toyota157.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/toyota158.jpg",
    name: "Toyota Avalon 2022",
    vin: "9S42F1FK3HWMZ85J1",
    date: "2022",
    price: 25000,
    hp: "180",
    gallery: [
      "images/cars/toyota158.jpg",
      "images/cars/toyota159.jpg",
      "images/cars/toyota160.jpg",
      "images/cars/toyota161.jpg",
      "images/cars/toyota162.jpg",
      "images/cars/toyota163.jpg",
      "images/cars/toyota164.jpg",
      "images/cars/toyota165.jpg",
    ],
    carbrand: "Toyota",
  },
  {
    id: Math.random(),
    picture: "images/cars/car1.jpg",
    name: "MAZDA MAZDA2 SPORT ",
    vin: "JM1DE1KZXE0******",
    date: "2014",
    price: 4000,
    hp: "80",
    gallery: [
      "images/cars/car2.jpg",
      "images/cars/car3.jpg",
      "images/cars/car4.jpg",
      "images/cars/car5.jpg",
    ],
    carbrand: "Mazda",
  },
  {
    id: Math.random(),
    picture: "images/cars/car6.jpg",
    name: " MAZDA 6 I ",
    vin: "1YVHZ8BH6B5******",
    date: "2011",
    price: 6000,
    hp: "165",
    gallery: [
      "images/cars/car7.jpg",
      "images/cars/car8.jpg",
      "images/cars/car9.jpg",
      "images/cars/car10.jpg",
    ],
    carbrand: "Mazda",
  },
  {
    id: Math.random(),
    picture: "images/cars/car11.jpg",
    name: "MAZDA 6 GRAND TOURING ",
    vin: "JM1GJ1W6XE1******",
    date: "2014",
    price: 10000,
    hp: "175",
    gallery: [
      "images/cars/car12.jpg",
      "images/cars/car13.jpg",
      "images/cars/car14.jpg",
      "images/cars/car15.jpg",
    ],
    carbrand: "Mazda",
  },
  {
    id: Math.random(),
    picture: "images/cars/car16.jpg",
    name: "MAZDA CX-5 SPORT ",
    vin: "JM3KFABMXJ1******",
    date: "2018",
    price: 25000,
    hp: "200",
    gallery: [
      "images/cars/car17.jpg",
      "images/cars/car18.jpg",
      "images/cars/car19.jpg",
      "images/cars/car20.jpg",
    ],
    carbrand: "Mazda",
  },
  {
    id: Math.random(),
    picture: "images/cars/car21.jpg",
    name: "MAZDA CX-3 TOURING",
    vin: "JM1DKDC73K1******",
    date: "2019",
    price: 23000,
    hp: "175",
    gallery: [
      "images/cars/car22.jpg",
      "images/cars/car23.jpg",
      "images/cars/car24.jpg",
      "images/cars/car25.jpg",
    ],
    carbrand: "Mazda",
  },
  {
    id: Math.random(),
    picture: "images/cars/car26.jpg",
    name: "MAZDA CX-5 GRAND TOURING",
    vin: "JM3KFBDM0L0******",
    date: "2020",
    price: 28000,
    hp: "200",
    gallery: [
      "images/cars/car27.jpg",
      "images/cars/car28.jpg",
      "images/cars/car29.jpg",
      "images/cars/car30.jpg",
    ],
    carbrand: "Mazda",
  },
  {
    id: Math.random(),
    picture: "images/cars/car31.jpg",
    name: "MAZDA 3 HATCHBACK",
    vin: "JM1BK343041******",
    date: "2004",
    price: 3000,
    hp: "120",
    gallery: [
      "images/cars/car32.jpg",
      "images/cars/car33.jpg",
      "images/cars/car34.jpg",
      "images/cars/car35.jpg",
    ],
    carbrand: "Mazda",
  },
  {
    id: Math.random(),
    picture: "images/cars/car36.jpg",
    name: "MAZDA MPV WAGON ",
    vin: "JM3LW28J850******",
    date: "2005",
    price: 8000,
    hp: "160",
    gallery: [
      "images/cars/car37.jpg",
      "images/cars/car38.jpg",
      "images/cars/car39.jpg",
      "images/cars/car40.jpg",
    ],
    carbrand: "Mazda",
  },
  {
    id: Math.random(),
    picture: "images/cars/car41.jpg",
    name: "MAZDA CX-5 GT",
    vin: "JM3KE4DE4D0******",
    date: "2013",
    price: 12000,
    hp: "180",
    gallery: [
      "images/cars/car42.jpg",
      "images/cars/car43.jpg",
      "images/cars/car44.jpg",
      "images/cars/car45.jpg",
    ],
    carbrand: "Mazda",
  },
  {
    id: Math.random(),
    picture: "images/cars/car46.jpg",
    name: "MAZDA CX-30",
    vin: "3MVDMBALXNM******",
    date: "2022",
    price: 35000,
    hp: "224",
    gallery: [
      "images/cars/car47.jpg",
      "images/cars/car48.jpg",
      "images/cars/car49.jpg",
      "images/cars/car50.jpg",
    ],
    carbrand: "Mazda",
  },
  {
    id: Math.random(),
    picture: "images/cars/1bm.jpg",
    name: "BMW X5",
    vin: "5UXKROC5XFO",
    date: "2015",
    price: 10000,
    hp: "306",
    gallery: [
      "images/cars/2bm.jpg",
      "images/cars/3bm.jpg",
      "images/cars/4bm.jpg",
      "images/cars/5bm.jpg",
      "images/cars/6bm.jpg",
    ],
    carbrand: "Bmw",
  },
  {
    id: Math.random(),
    picture: "images/cars/7bm.jpg",
    name: "BMW X5 M",
    vin: "5YMKT6C35HO",
    date: "2017",
    price: 12000,
    hp: "300",
    gallery: [
      "images/cars/8bm.jpg",
      "images/cars/9bm.jpg",
      "images/cars/10bm.jpg",
      "images/cars/11bm.jpg",
      "images/cars/12bm.jpg",
    ],
    carbrand: "Bmw",
  },
  {
    id: Math.random(),
    picture: "images/cars/13bm.jpg",
    name: "BMW X6 ",
    vin: "5UXKU2C56GO",
    date: "2016",
    price: 15000,
    hp: "306",
    gallery: [
      "images/cars/14bm.jpg",
      "images/cars/15bm.jpg",
      "images/cars/16bm.jpg",
      "images/cars/17bm.jpg",
      "images/cars/18bm.jpg",
    ],
    carbrand: "Bmw",
  },
  {
    id: Math.random(),
    picture: "images/cars/19bm.jpg",
    name: "BMW X6 ",
    vin: "5UXKU6C5EKL",
    date: "2019",
    price: 62000,
    hp: "306",
    gallery: [
      "images/cars/20bm.jpg",
      "images/cars/21bm.jpg",
      "images/cars/22bm.jpg",
      "images/cars/23bm.jpg",
      "images/cars/24bm.jpg",
    ],
    carbrand: "Bmw",
  },
  {
    id: Math.random(),
    picture: "images/cars/25bm.jpg",
    name: "BMW 750 LXL ",
    vin: "WBAYF8C5XDD",
    date: "2013",
    price: 22100,
    hp: "258~",
    gallery: [
      "images/cars/26bm.jpg",
      "images/cars/27bm.jpg",
      "images/cars/28bm.jpg",
      "images/cars/29bm.jpg",
      "images/cars/30bm.jpg",
    ],
    carbrand: "Bmw",
  },
  {
    id: Math.random(),
    picture: "images/cars/31bm.jpg",
    name: "BMW X5  ",
    vin: "5UXCR6C53KL",
    date: "2019",
    price: 37000,
    hp: "249~",
    gallery: [
      'images/cars/31bm.jpg',
      "images/cars/32bm.jpg",
      "images/cars/33bm.jpg",
      "images/cars/34bm.jpg",
      "images/cars/35bm.jpg",
      "images/cars/36bm.jpg",
    ],
    carbrand: "Bmw",
  },
  {
    id: Math.random(),
    picture: "images/cars/37bm.jpg",
    name: "BMW X5  ",
    vin: "5UUXKR2C50GO",
    date: "2016",
    price: 29000,
    hp: "306~",
    gallery: [
      "images/cars/38bm.jpg",
      "images/cars/39bm.jpg",
      "images/cars/40bm.jpg",
      "images/cars/41bm.jpg",
      "images/cars/42bm.jpg",
    ],
    carbrand: "Bmw",
  },
  {
    id: Math.random(),
    picture: "images/cars/43bm.jpg",
    name: "BMW 750 LI ",
    vin: "WBAKB8C58AC",
    date: "2010",
    price: 37000,
    hp: "445~",
    gallery: [
      "images/cars/44bm.jpg",
      "images/cars/45bm.jpg",
      "images/cars/46bm.jpg",
      "images/cars/47bm.jpg",
      "images/cars/48bm.jpg",
    ],
    carbrand: "Bmw",
  },
  {
    id: Math.random(),
    picture: "images/cars/mercedes_GLS_1.jpg",
    name: "Mercedes-Benz GLS 550 4MATIC",
    vin: "4JGDF7DE5JB007090",
    date: "2018",
    price: 31460,
    hp: "449",
    gallery: [
      "images/cars/mercedes_GLS_1.jpg",
      "images/cars/mercedes_GLS_2.jpg",
      "images/cars/mercedes_GLS_3.jpg",
      "images/cars/mercedes_GLS_4.jpg",
      "images/cars/mercedes_GLS_5.jpg",
      "images/cars/mercedes_GLS_6.jpg",
      "images/cars/mercedes_GLS_7.jpg",
    ],
    carbrand: "Mercedes",
  },
  {
    id: Math.random(),
    picture: "images/cars/mercedes_CLS_1.jpg",
    name: "Mercedes-Benz CLS 450 4MATIC",
    vin: "WK2J5KB0MA089785",
    date: "2021",
    price: 35000,
    hp: "362",
    gallery: [
      "images/cars/mercedes_CLS_1.jpg",
      "images/cars/mercedes_CLS_2.jpg",
      "images/cars/mercedes_CLS_3.jpg",
      "images/cars/mercedes_CLS_4.jpg",
      "images/cars/mercedes_CLS_5.jpg",
      "images/cars/mercedes_CLS_6.jpg",
      "images/cars/mercedes_CLS_7.jpg",
    ],
    carbrand: "Mercedes",
  },
  {
    id: Math.random(),
    picture: "images/cars/mercedes_S_1.jpg",
    name: "MERCEDES-BENZ S 63 AMG",
    vin: "WDDXJ7JB0FA001775",
    date: "2015",
    price: 75000,
    hp: "577",
    gallery: [
      "images/cars/mercedes_S_1.jpg",
      "images/cars/mercedes_S_2.jpg",
      "images/cars/mercedes_S_3.jpg",
      "images/cars/mercedes_S_4.jpg",
      "images/cars/mercedes_S_5.jpg",
      "images/cars/mercedes_S_6.jpg",
      "images/cars/mercedes_S_7.jpg",
      "images/cars/mercedes_S_8.jpg",
    ],
    carbrand: "Mercedes",
  },
  {
    id: Math.random(),
    picture: "images/cars/mercedes_E_1.jpg",
    name: "Mercedes-Benz E 63 4MATIC",
    vin: "WDDZF4JB7HA073200",
    date: "2017",
    price: 24900,
    hp: "245",
    gallery: [
      "images/cars/mercedes_E_1.jpg",
      "images/cars/mercedes_E_2.jpg",
      "images/cars/mercedes_E_3.jpg",
      "images/cars/mercedes_E_4.jpg",
      "images/cars/mercedes_E_5.jpg",
      "images/cars/mercedes_E_6.jpg",
      "images/cars/mercedes_E_7.jpg",
    ],
    carbrand: "Mercedes",
  },
  {
    id: Math.random(),
    picture: "images/cars/mercedes_CLA_1.jpg",
    name: " MERCEDES-BENZ CLA 250 4MATIC",
    vin: "WDDSJ4GB9JN555351",
    date: "2018",
    price: 27990,
    hp: "208",
    gallery: [
      "images/cars/mercedes_CLA_1.jpg",
      "images/cars/mercedes_CLA_2.jpg",
      "images/cars/mercedes_CLA_3.jpg",
      "images/cars/mercedes_CLA_4.jpg",
      "images/cars/mercedes_CLA_5.jpg",
      "images/cars/mercedes_CLA_6.jpg",
      "images/cars/mercedes_CLA_7.jpg",
    ],
    carbrand: "Mercedes",
  },
  {
    id: Math.random(),
    picture: "images/cars/mercedes_E_02_1.jpg",
    name: "Mercedes-Benz E 550 4MATIC",
    vin: "W1KXF8DB7NB0858890",
    date: "2022",
    price: 51660,
    hp: "245",
    gallery: [
      "images/cars/mercedes_E_02_1.jpg",
      "images/cars/mercedes_E_02_2.jpg",
      "images/cars/mercedes_E_02_3.jpg",
      "images/cars/mercedes_E_02_4.jpg",
      "images/cars/mercedes_E_02_5.jpg",
      "images/cars/mercedes_E_02_6.jpg",
      "images/cars/mercedes_E_02_7.jpg",
      "images/cars/mercedes_E_02_8.jpg",
    ],
    carbrand: "Mercedes",
  },
  {
    id: Math.random(),
    picture: "images/cars/ford1.jpg",
    name: "FORD ESCAPE SE",
    vin: "1FMCU0GD7JU******",
    date: "2018",
    price: 4950,
    hp: "184",
    gallery: [
      "images/cars/ford-1-1.jpg",
      "images/cars/ford-1-2.jpg",
      "images/cars/ford-1-3.jpg",
      "images/cars/ford-1-4.jpg",
      "images/cars/ford1-5.jpg",
    ],
    carbrand: "Ford",
  },
  {
    id: Math.random(),
    picture: "images/cars/ford2.jpg",
    name: " FORD FUSION SE",
    vin: "3FA6P0H79HR******",
    date: "2017",
    price: 5000,
    hp: "141",
    gallery: [
      "images/cars/ford2-1.jpg",
      "images/cars/ford2-2.jpg",
      "images/cars/ford2-3.jpg",
      "images/cars/ford2-4.jpg",
      "images/cars/ford2-5.jpg",
    ],
    carbrand: "Ford",
  },
  {
    id: Math.random(),
    picture: "images/cars/ford3.jpg",
    name: "FORD EXPLORER XLT",
    vin: "1FM5K7D80KG******",
    date: "2019",
    price: 21000,
    hp: "347",
    gallery: [
      "images/cars/ford3-1.jpg",
      "images/cars/ford3-2.jpg",
      "images/cars/ford3-3.jpg",
      "images/cars/ford3-4.jpg",
      "images/cars/ford3-5.jpg",
    ],
    carbrand: "Ford",
  },
  {
    id: Math.random(),
    picture: "images/cars/ford4.jpg",
    name: "2016 FORD MUSTANG",
    vin: "1FATP8EM9G5******",
    date: "2016",
    price: 3500,
    hp: "435",
    gallery: [
      "images/cars/ford4-1.jpg",
      "images/cars/ford4-2.jpg",
      "images/cars/ford4-3.jpg",
      "images/cars/ford4-4.jpg",
      "images/cars/ford4-5.jpg",
    ],
    carbrand: "Ford",
  },
  {
    id: Math.random(),
    picture: "images/cars/ford5.jpg",
    name: " FORD EDGE SEL",
    vin: "2FMPK4J94KB******",
    date: "2019",
    price: 2200,
    hp: "250",
    gallery: [
      "images/cars/ford5-1.jpg",
      "images/cars/ford5-2.jpg",
      "images/cars/ford5-3.jpg",
      "images/cars/ford5-4.jpg",
      "images/cars/ford5-5.jpg",
    ],
    carbrand: "Ford",
  },
  {
    id: Math.random(),
    picture: "images/cars/ford6.jpg",
    name: " FORD ESCAPE SE",
    vin: "1FMCU9GD6JU******",
    date: "2018",
    price: 2000,
    hp: "184",
    gallery: [
      "images/cars/ford6-1.jpg",
      "images/cars/ford6-2.jpg",
      "images/cars/ford6-3.jpg",
      "images/cars/ford6-4.jpg",
      "images/cars/ford6-5.jpg",
    ],
    carbrand: "Ford",
  },
  {
    id: Math.random(),
    picture: "images/cars/ford7.jpg",
    name: " FORD FOCUS SEL ",
    vin: "1FADP3M2XHL******",
    date: "2017 ",
    price: 1000,
    hp: "125",
    gallery: [
      "images/cars/ford7-1.jpg",
      "images/cars/ford7-2.jpg",
      "images/cars/ford7-3.jpg",
      "images/cars/ford7-4.jpg",
      "images/cars/ford7-5.jpg",
    ],
    carbrand: "Ford",
  },
  {
    id: Math.random(),
    picture: "images/cars/ford8.jpg",
    name: "FORD ESCAPE SE",
    vin: "1FMCU0G98EU******",
    date: "2014",
    price: 3400,
    hp: "187",
    gallery: [
      "images/cars/ford8-1.jpg",
      "images/cars/ford8-2.jpg",
      "images/cars/ford8-3.jpg",
      "images/cars/ford8-4.jpg",
      "images/cars/ford8-5.jpg",
    ],
    carbrand: "Ford",
  },
  {
    id: Math.random(),
    picture: "images/cars/ford9.jpg",
    name: " FORD FUSION SE",
    vin: "3FAHP0HG9AR******",
    date: "2010",
    price: 1500,
    hp: "156",
    gallery: [
      "images/cars/ford9-1.jpg",
      "images/cars/ford9-2.jpg",
      "images/cars/ford9-3.jpg",
      "images/cars/ford9-4.jpg",
      "images/cars/ford9-5.jpg",
    ],
    carbrand: "Ford",
  },
  {
    id: Math.random(),
    picture: "images/cars/ford10.jpg",
    name: " FORD FUSION SE",
    vin: "3FA6P0H74FR******",
    date: "2015",
    price: 1200,
    hp: "175",
    gallery: [
      "images/cars/ford10-1.jpg",
      "images/cars/ford10-2.jpg",
      "images/cars/ford10-3.jpg",
      "images/cars/ford10-4.jpg",
      "images/cars/ford10-5.jpg",
    ],
    carbrand: "Ford",
  },
  {
    id: Math.random(),
    picture: "images/cars/Q8_1.jpg",
    name: "Audi Q8 50 TDI",
    vin: "WAU**************",
    date: "2023",
    price: 178024,
    hp: 286,
    gallery: [
      "images/cars/Q8_2.webp",
      "images/cars/Q8_3.webp",
      "images/cars/Q8_4.webp",
      "images/cars/Q8_5.webp",
    ],
    carbrand: "Audi",
  },
  {
    id: Math.random(),
    picture: "images/cars/R7_1.webp",
    name: "Audi R7",
    vin: "WAU**************",
    date: "2011",
    price: 16443,
    hp: 300,
    gallery: [
      "images/cars/R7_2.webp",
      "images/cars/R7_3.webp",
      "images/cars/R7_4.webp",
      "images/cars/R7_5.webp",
    ],
    carbrand: "Audi",
  },
  {
    id: Math.random(),
    picture: "images/cars/R8_1.webp",
    name: "Audi R8 V10 performance",
    vin: "WAU**************",
    date: "2020",
    price: 194112,
    hp: 620,
    gallery: [
      "images/cars/R8_2.webp",
      "images/cars/R8_3.webp",
      "images/cars/R8_4.webp",
    ],
    carbrand: "Audi",
  },
  {
    id: Math.random(),
    picture: "images/cars/A6_1.webp",
    name: "Audi A6 45 TFSI Long",
    vin: "WAU**************",
    date: "2023",
    price: 101088,
    hp: 245,
    gallery: [
      "images/cars/A6_2.webp",
      "images/cars/A6_3.webp",
      "images/cars/A6_4.webp",
      "images/cars/A6_5.webp",
    ],
    carbrand: "Audi",
  },
  {
    id: Math.random(),
    picture: "images/cars/S5_1.webp",
    name: "Audi S5",
    vin: "WAU**************",
    date: "2012",
    price: 16182,
    hp: 333,
    gallery: [
      "images/cars/S5_2.webp",
      "images/cars/S5_3.webp",
      "images/cars/S4_4.webp",
      "images/cars/S5_5.webp",
    ],
    carbrand: "Audi",
  },
  {
    id: Math.random(),
    picture: "images/cars/RSQ8_1.webp",
    name: "Audi RS Q8",
    vin: "WAU**************",
    date: "2023",
    price: 269534,
    hp: 600,
    gallery: [
      "images/cars/RSQ8_2.webp",
      "images/cars/RSQ8_3.webp",
      "images/cars/RSQ8_4.webp",
      "images/cars/RSQ8_5.webp",
    ],
    carbrand: "Audi",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-1.jpg",
    name: "Lexus LX 570",
    vin: "123W54EJK89478568",
    date: "2018",
    price: 78000,
    hp: "383",
    gallery: [
      "images/cars/img-2.jpg",
      "images/cars/img-3.jpg",
      "images/cars/img-4.jpg",
      "images/cars/img-5.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-6.webp",
    name: "Lexus RX 350",
    vin: "JUTN2059YS785983L",
    date: "2019",
    price: 30300,
    hp: "320",
    gallery: [
      "images/cars/img-7.webp",
      "images/cars/img-8.webp",
      "images/cars/img-9.webp",
      "images/cars/img-10.webp",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-11.webp",
    name: "Lexus LX600$",
    vin: "1258HSIME76KDDVI5",
    date: "2023",
    price: 220200,
    hp: "420",
    gallery: [
      "images/cars/img-12.webp",
      "images/cars/img-13.webp",
      "images/cars/img-14.webp",
      "images/cars/img-15.webp",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-16.jpg",
    name: "Lexus ES 300H",
    vin: "A9EKDD7469885522S",
    date: "2019",
    price: 34000,
    hp: "200",
    gallery: [
      "images/cars/img-17.jpg",
      "images/cars/img-18.jpg",
      "images/cars/img-19.jpg",
      "images/cars/img-20.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-21.jpg",
    name: "Lexus NX 300",
    vin: "HGEI458D6EG424836",
    date: "2021",
    price: 34000,
    hp: "197",
    gallery: [
      "images/cars/img-22.jpg",
      "images/cars/img-23.jpg",
      "images/cars/img-24.jpg",
      "images/cars/img-25.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-26.jpg",
    name: "Lexus NX 300",
    vin: "AQB52453HUU467MHI48",
    date: "2018",
    price: 21500,
    hp: "190",
    gallery: [
      "images/cars/img-27.jpg",
      "images/cars/img-28.jpg",
      "images/cars/img-29.jpg",
      "images/cars/img-30.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-31.jpg",
    name: "Lexus IS 200",
    vin: "5462GMX6998562UTSN",
    date: "2015",
    price: 14900,
    hp: "185",
    gallery: [
      "images/cars/img-32.jpg",
      "images/cars/img-33.jpg",
      "images/cars/img-34.jpg",
      "images/cars/img-35.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-36.jpeg",
    name: "Lexus NX",
    vin: "QTG6983018H07WF53",
    date: "2015",
    price: 30000,
    hp: "240",
    gallery: [
      "images/cars/img-37.jpeg",
      "images/cars/img-38.jpeg",
      "images/cars/img-39.jpeg",
      "images/cars/img-40.jpeg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-41.jpg",
    name: "LEXUS RX 450H",
    vin: "2T2YGMDA4NC584KG2",
    date: "2022",
    price: 45000,
    hp: "245",
    gallery: [
      "images/cars/img-42.jpg",
      "images/cars/img-43.jpg",
      "images/cars/img-44.jpg",
      "images/cars/img-45.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-46.jpg",
    name: "LEXUS LS 460",
    vin: "AYEM58432298U56SR",
    date: "2013",
    price: 24000,
    hp: "367",
    gallery: [
      "images/cars/img-47.jpg",
      "images/cars/img-48.jpg",
      "images/cars/img-49.jpg",
      "images/cars/img-50.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-51.jpg",
    name: "LEXUS CT 200",
    vin: "UISL56U4355U57CX9",
    date: "2012",
    price: 10000,
    hp: "134",
    gallery: [
      "images/cars/img-52.jpg",
      "images/cars/img-53.jpg",
      "images/cars/img-54.jpg",
      "images/cars/img-55.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-56.jpg",
    name: "LEXUS GX 460",
    vin: "IS486JITCE648YNQP",
    date: "2020",
    price: 20000,
    hp: "305",
    gallery: [
      "images/cars/img-57.jpg",
      "images/cars/img-58.jpg",
      "images/cars/img-59.jpg",
      "images/cars/img-60.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-61.jpg",
    name: "LEXUS IS 300",
    vin: "ISLU5793IK49HYIOC",
    date: "2017",
    price: 12000,
    hp: "245",
    gallery: [
      "images/cars/img-62.jpg",
      "images/cars/img-63.jpg",
      "images/cars/img-64.jpg",
      "images/cars/img-65.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-66.jpg",
    name: "LEXUS LX 470 ",
    vin: "IYWN486JB523MZWWI",
    date: "2003",
    price: 14500,
    hp: "275",
    gallery: [
      "images/cars/img-67.jpg",
      "images/cars/img-68.jpg",
      "images/cars/img-69.jpg",
      "images/cars/img-70.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-71.jpg",
    name: "LEXUS GS 350",
    vin: "HLAI4839255UWOA8Q",
    date: "2013",
    price: 7000,
    hp: "317",
    gallery: [
      "images/cars/img-72.jpg",
      "images/cars/img-73.jpg",
      "images/cars/img-74.jpg",
      "images/cars/img-75.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-76.jpg",
    name: "LEXUS RC 200T",
    vin: "WTJSOIA57931OU58E",
    date: "2016",
    price: 13000,
    hp: "245",
    gallery: [
      "images/cars/img-77.jpg",
      "images/cars/img-78.jpg",
      "images/cars/img-79.jpg",
      "images/cars/img-80.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-81.jpg",
    name: "LEXUS RX 400",
    vin: "GSNO486522IZXOL46",
    date: "2006",
    price: 8500,
    hp: "270",
    gallery: [
      "images/cars/img-82.jpg",
      "images/cars/img-83.jpg",
      "images/cars/img-84.jpg",
      "images/cars/img-85.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-86.jpg",
    name: "LEXUS LS 460L ",
    vin: "UDNSLISM57JU95736",
    date: "2011",
    price: 7500,
    hp: "380",
    gallery: [
      "images/cars/img-87.jpg",
      "images/cars/img-88.jpg",
      "images/cars/img-89.jpg",
      "images/cars/img-90.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-91.jpg",
    name: "LEXUS GS 350",
    vin: "USPENJ57964YSNLAN",
    date: "2013",
    price: 9000,
    hp: "310",
    gallery: [
      "images/cars/img-92.jpg",
      "images/cars/img-93.jpg",
      "images/cars/img-94.jpg",
      "images/cars/img-95.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-96.jpg",
    name: "LEXUS IS 200T",
    vin: "UYSH78546F43SEF57",
    date: "2016",
    price: 15000,
    hp: "250",
    gallery: [
      "images/cars/img-97.jpg",
      "images/cars/img-98.jpg",
      "images/cars/img-99.jpg",
      "images/cars/img-100.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-101.jpg",
    name: "LEXUS LX 570",
    vin: "8976DFR7836SW79QA",
    date: "2017",
    price: 80000,
    hp: "370",
    gallery: [
      "images/cars/img-102.jpg",
      "images/cars/img-103.jpg",
      "images/cars/img-104.jpg",
      "images/cars/img-105.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/img-106.jpg",
    name: "LEXUS GX 460 ",
    vin: "QPIS609940456YSO5",
    date: "2018",
    price: 32000,
    hp: "296",
    gallery: [
      "images/cars/img-107.jpg",
      "images/cars/img-108.jpg",
      "images/cars/img-109.jpg",
      "images/cars/img-110.jpg",
    ],
    carbrand: "Lexus",
  },
  {
    id: Math.random(),
    picture: "images/cars/1do.jpg",
    name: "DODGE CHALLENGER SXT",
    vin: "2C3CDZAG3PH******",
    date: "2023",
    price: 35000,
    hp: "450",
    gallery: [
      "images/cars/2do.jpg",
      "images/cars/3do.jpg",
      "images/cars/4do.jpg",
      "images/cars/5do.jpg",
    ],
    carbrand: "Dodge",
  },
  {
    id: Math.random(),
    picture: "images/cars/6do.jpg",
    name: "DODGE CHARGER SRT HELLCAT",
    vin: "2C3CDXL95JH******",
    date: "2018",
    price: 25000,
    hp: "400",
    gallery: [
      "images/cars/7do.jpg",
      "images/cars/8do.jpg",
      "images/cars/9do.jpg",
      "images/cars/10do.jpg",
    ],
    carbrand: "Dodge",
  },
  {
    id: Math.random(),
    picture: "images/cars/11do.jpg",
    name: "DODGE DURANGO R/T",
    vin: "1C4SDJCTXNC******",
    date: "2022",
    price: 15000,
    hp: "174",
    gallery: [
      "images/cars/12do.jpg",
      "images/cars/13do.jpg",
      "images/cars/14do.jpg",
      "images/cars/15do.jpg",
    ],
    carbrand: "Dodge",
  },
  {
    id: Math.random(),
    picture: "images/cars/16do.jpg",
    name: " DODGE RAM 1500 ",
    vin: "1D7RV1CT3AS******",
    date: "2010",
    price: 10000,
    hp: "129",
    gallery: [
      "images/cars/17do.jpg",
      "images/cars/18do.jpg",
      "images/cars/19do.jpg",
      "images/cars/20do.jpg",
    ],
    carbrand: "Dodge",
  },
  {
    id: Math.random(),
    picture: "images/cars/21do.jpg",
    name: "DODGE DART SXT",
    vin: "1C3CDFBH4DD******",
    date: "2013",
    price: 7900,
    hp: "140",
    gallery: [
      "images/cars/22do.jpg",
      "images/cars/23do.jpg",
      "images/cars/24do.jpg",
      "images/cars/25do.jpg",
    ],
    carbrand: "Dodge",
  },

  {
    id: Math.random(),
    picture: "images/cars/2016 NISSAN ROGUE S-1.jpg",
    name: "NISSAN ROGUE S-1",
    vin: "5N1AT2MV4GC66GFS4C",
    date: "2016",
    price: 1000,
    hp: "250",
    gallery: [
      "images/cars/2016 NISSAN ROGUE S-1.jpg",
      "images/cars/2016 NISSAN ROGUE S-2.jpg",
      "images/cars/2016 NISSAN ROGUE S-3.jpg",
      "images/cars/2016 NISSAN ROGUE S-4.jpg",
      "images/cars/2016 NISSAN ROGUE S-5.jpg",
    ],
    carbrand: "Nissan",
  },
  {
    id: Math.random(),
    picture: "images/cars/2017 NISSAN NV200 2.5S-1.jpg",
    name: " NISSAN NV200 2.5S",
    vin: "3N6CM0KN8HKDSA45A6",
    date: "2017",
    price: 1000,
    hp: "120",
    gallery: [
      "images/cars/2017 NISSAN NV200 2.5S-1.jpg",
      "images/cars/2017 NISSAN NV200 2.5S-2.jpg",
      "images/cars/2017 NISSAN NV200 2.5S-3.jpg",
      "images/cars/2017 NISSAN NV200 2.5S-4.jpg",
      "images/cars/2017 NISSAN NV200 2.5S-5.jpg",
    ],
    carbrand: "Nissan",
  },
  {
    id: Math.random(),
    picture: "images/cars/2016 NISSAN ALTIMA 2.5-1.jpg",
    name: "NISSAN ALTIMA 2.5",
    vin: "3N6CM0KN8HKDSA45A6",
    date: "2016",
    price: 1000,
    hp: "200",
    gallery: [
      "images/cars/2016 NISSAN ALTIMA 2.5-1.jpg",
      "images/cars/2016 NISSAN ALTIMA 2.5-2.jpg",
      "images/cars/2016 NISSAN ALTIMA 2.5-3.jpg",
      "images/cars/2016 NISSAN ALTIMA 2.5-4.jpg",
      "images/cars/2016 NISSAN ALTIMA 2.5-5.jpg",
    ],
    carbrand: "Nissan",
  },
  {
    id: Math.random(),
    picture: "images/cars/2021 NISSAN SENTRA S-1.jpg",
    name: "NISSAN SENTRA S",
    vin: "3N1AB8BV5MY4GDFS4",
    date: "2021",
    price: 1000,
    hp: "200",
    gallery: [
      "images/cars/2021 NISSAN SENTRA S-1.jpg",
      "images/cars/2021 NISSAN SENTRA S-2.jpg",
      "images/cars/2021 NISSAN SENTRA S-3.jpg",
      "images/cars/2021 NISSAN SENTRA S-4.jpg",
      "images/cars/2021 NISSAN SENTRA S-5.jpg",
    ],
    carbrand: "Nissan",
  },
  {
    id: Math.random(),
    picture: "images/cars/2007 NISSAN TITAN XE-1.jpg",
    name: "NISSAN TITAN XE",
    vin: "1N6BA07B87NA4SD8",
    date: "2007",
    price: 4000,
    hp: "200",
    gallery: [
      "images/cars/2007 NISSAN TITAN XE-1.jpg",
      "images/cars/2007 NISSAN TITAN XE-2.jpg",
      "images/cars/2007 NISSAN TITAN XE-3.jpg",
      "images/cars/2007 NISSAN TITAN XE-4.jpg",
      "images/cars/2007 NISSAN TITAN XE-5.jpg",
    ],
    carbrand: "Nissan",
  },
].sort(() => Math.random() - 0.5);

export const carNames = [
  'Dodge',
  'Ford',
  'Mazda',
  'Mercedes',
  'Bmw',
  'Audi',
  'Lexus',
  'Toyota',
  'Nissan'
].sort();

export const Autcion = [
  "images/Auction/Auction_1.jpeg",
  "images/Auction/Auction_2.jpg",
  "images/Auction/Auction_3.jpg",
];

export const logistic = [
  'images/logistic/logisticsreserve1.jpg',
  'images/logistic/logisticsreserve2.webp',
  'images/logistic/logisticsreserve3.png',
  'images/logistic/logisticsreserve4.jpg',  
  'images/logistic/logisticsreserve5.jpg',  
];


export const logins = []


export const color = [
  '#A0A4B8',
  '#0C6291',
  '#ED1C24',
  '#0B2545',
  '#BFBCCB',
  '#BBE5ED',
].sort(() => Math.random() - 0.5);

export const fonts = [
  'Alfa Slab One, serif',
  'Merienda, cursive',
  'Abril Fatface, serif',
  'Anton, sans-serif',
  'Tac One, sans-serif',
  'Reddit ',
   "Rubik Scribble, system-ui",
   "Rancho, cursive ",
   "Julee, cursive"
]

export const aboutTeam = [
  {
    id:Math.random(),
    name : 'Jeff Liaw',
    position : 'Chief Executive Officer',
    picture : 'images/aboutteam/1.png',
    text : 'Jeff Liaw has served as CEO of Drive & Bid Auto Company since April 2024. He served as Co-CEO from March 2022 to April 2024. Jeff joined Drive & Bid Auto Company in 2016 as CFO, and additionally served as President of the company from 2019-2022. Prior to Drive & Bid Auto Company, Jeff served as the CFO of Fleetpride, the largest independent distributor of aftermarket truck parts in the U.S., which was owned by TPG Capital, where he was a principal investor overseeing private equity investments in the financial services and industrial sectors. Jeff earned his MBA from Harvard Business School with highest distinction as a Baker Scholar, Siebel Scholar, and co-president of his class, and received his bachelor’s '
  },
  {
    id:Math.random(),
    name : 'David Kang',
    position : 'Chief Marketing Officer',
    picture : 'images/aboutteam/2.jpg',
    text : 'David Kang leads Drive & Bid Auto Company’s marketing functions, including marketing analytics, brand, communications, digital, and global member development as well as leading our Cash for Cars business. David has extensive experience in marketing and data analytics, serving most recently as SVP, Data Insights and CMO, Consumer Auto Finance at Capital One. Prior to Capital One he held various leadership positions at McKinsey & Company, supporting clients across the firm’s Travel, Transportation and Logistics practice. David holds an MBA from Harvard Business School and a bachelor’s degree in economics and a master’s degree in statistics from Harvard University.'
  },
  {
    id:Math.random(),
    name : 'Paul Kirkpatrick',
    position : 'Chief Legal Officer and Corporate Secretary',
    picture : 'images/aboutteam/3.jpg',
    text : 'Paul leads Drive & Bid Auto Company’s legal department and helps guide the company in all legal matters, including in the areas of corporate law, commercial contracts, real estate, compliance, litigation, and government affairs. Paul has extensive experience as a general counsel and chief legal officer, most recently at BayoTech, Inc., Omnitracs (including through its recent acquisition by Solera Global Holdings), and a decade at Commercial Metals Company, a Fortune 500 NYSE listed company. Kirkpatrick holds a law degree from the Dedman School of Law at Southern Methodist University and a bachelor’s degree in History from Baylor University. Paul joined Drive & Bid Auto Company in 2022.'
  },
  {
    id:Math.random(),
    name : 'Neel Madhvani',
    position : 'Chief Product Officer',
    picture : 'images/aboutteam/4.jpg',
    text : 'Neel Madhvani leads Drive & Bid Auto Company’s new product development initiatives, in close partnership with sales, marketing, operations and technology. Neel has extensive product development experience, serving most recently as VP, Product at Chewy and previously in product development, marketing, strategy, and innovation roles at Boxed and Staples. Neel holds an MBA and an MS in Information Systems from the Questrom School of Business at Boston University and a bachelor’s degree in writing from The Johns Hopkins University.',
  },
  {
    id:Math.random(),
    name : 'Steve Powers',
    position : 'Chief Business Development Officer',
    picture : 'images/aboutteam/5.png',
    text : 'Steve Powers leads Drive & Bid Auto Company’s real estate acquisition and facility development teams, as well as initiatives to drive growth across Drive & Bid Auto Company’s complementary lines of business, including Purple Wave and National Powersport Auctions (NPA).Steve began his career with Drive & Bid Auto Company over 40 years ago, most recently serving as the company’s COO, a role in which he led major initiatives such as real estate acquisition and development, catastrophic event response and the development of our logistics fleet. Prior to his role as COO, Steve was VP of Operations for Drive & Bid Auto Company’s Eastern Division.',
  },
  {
    id:Math.random(),
    name : 'Rama Prasad',
    position : 'Chief Technology Officer',
    picture : 'images/aboutteam/6.png',
    text : 'Rama Prasad was appointed Chief Technology Officer (CTO) in 2014, and brought more than 10 years of executive experience in the technology space. Previously, Prasad served as Senior Vice President and Chief Information Officer of Gogo Inc. He also worked in various technology roles at companies like Orbitz, US Cellular, Ameritech (AT& T), and Sprint. He is a graduate of the Executive Management Program at Northwestern University, and holds a Master of Science in Computer Science from the University of Missouri – Rolla and a bachelor’s degree in engineering from Osmania University',
  },
  {
    id:Math.random(),
    name : 'Leah Stearns',
    position : 'Chief Financial Officer',
    picture : 'images/aboutteam/7.jpg',
    text : 'Leah Stearns, Chief Financial Officer (CFO) of Drive & Bid Auto Company leads Drive & Bid Auto Company’s finance and accounting functions to help enable the company’s continuing profitable growth. She is a seasoned Fortune 500 executive, serving most recently as chief financial officer of CBRE, a global leader in commercial real estate services and investments, and previously in financial and operational leadership roles at American Tower. She holds an MBA from Boston College’s Carroll School of Management and a bachelor’s degree in finance from the Questrom School of Business at Boston University. Leah joined Drive & Bid Auto Company in 2022.',
  },
  {
    id:Math.random(),
    name : 'Rob Vannuccini',
    position : 'Chief Sales Officer',
    picture : 'images/aboutteam/8.png',
    text : 'Rob Vannuccini, Chief Sales Officer (CSO) of Drive & Bid Auto Company, leads one of the top sales teams in the automotive remarketing industry. Before he was appointed as CSO in 2010, he held many positions at Drive & Bid Auto Company since joining in 1994, including Vice President of National Accounts and Midwest Regional Account Manager. He brought vast experience and leadership skills he gained as the Midwest Regional Manager of NER Auction Systems and the Assistant Vice President of Fleet Financial Group. He received his bachelor’s degree in Business Administration in Banking and Finance from Hofstra University.',
  },
  {
    id:Math.random(),
    name : 'Hessel Verhage',
    position : 'Chief Operating Officer',
    picture : 'images/aboutteam/9.jpg',
    text : 'Hessel Verhage leads Drive & Bid Auto Company’s operations across more than 200 locations, optimizing processes and technology to ensure excellent service for Drive & Bid Auto Company’s sellers and members. Hessel brings extensive operational leadership experience to Drive & Bid Auto Company. Most recently, he served as an executive at DB Schenker, where he led their global contract logistics operations. Hessel is a veteran of the US Army and holds a bachelor’s degree in economics from East Carolina University.',
  },
]

